### ISSUE TITLE
lz77x.c isn't outputting a file?

### ISSUE THREAD

**Issue by bryc** [martincameron/lz77x#1]
```
File length: 742
Compressed length: 638
Okay.
```
Compression seems to work but it doesn't output the compressed file or have a mode for compress/decompress.

**Comment by martincameron** [comment]
It's really just for testing the algorithm, but I've put in the required functionality anyway!

**Comment by bryc** [comment]
Hey thanks! I'm not that great at C so simple single file implementations that don't need -std=c99 and whatnot are in short supply.
